/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProcessosRouteImport } from './routes/_app.processos'
import { Route as AppPacientesRouteImport } from './routes/_app.pacientes'
import { Route as AppMarcasRouteImport } from './routes/_app.marcas'
import { Route as AppFornecimentosRouteImport } from './routes/_app.fornecimentos'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppEstadosRouteImport } from './routes/_app.estados'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProcessosRoute = AppProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppMarcasRoute = AppMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecimentosRoute = AppFornecimentosRouteImport.update({
  id: '/fornecimentos',
  path: '/fornecimentos',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEstadosRoute = AppEstadosRouteImport.update({
  id: '/estados',
  path: '/estados',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/estados': typeof AppEstadosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/fornecimentos': typeof AppFornecimentosRoute
  '/marcas': typeof AppMarcasRoute
  '/pacientes': typeof AppPacientesRoute
  '/processos': typeof AppProcessosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/estados': typeof AppEstadosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/fornecimentos': typeof AppFornecimentosRoute
  '/marcas': typeof AppMarcasRoute
  '/pacientes': typeof AppPacientesRoute
  '/processos': typeof AppProcessosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/estados': typeof AppEstadosRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/fornecimentos': typeof AppFornecimentosRoute
  '/_app/marcas': typeof AppMarcasRoute
  '/_app/pacientes': typeof AppPacientesRoute
  '/_app/processos': typeof AppProcessosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/estados'
    | '/financeiro'
    | '/fornecimentos'
    | '/marcas'
    | '/pacientes'
    | '/processos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/estados'
    | '/financeiro'
    | '/fornecimentos'
    | '/marcas'
    | '/pacientes'
    | '/processos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/estados'
    | '/_app/financeiro'
    | '/_app/fornecimentos'
    | '/_app/marcas'
    | '/_app/pacientes'
    | '/_app/processos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/processos': {
      id: '/_app/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof AppProcessosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes': {
      id: '/_app/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marcas': {
      id: '/_app/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof AppMarcasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fornecimentos': {
      id: '/_app/fornecimentos'
      path: '/fornecimentos'
      fullPath: '/fornecimentos'
      preLoaderRoute: typeof AppFornecimentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estados': {
      id: '/_app/estados'
      path: '/estados'
      fullPath: '/estados'
      preLoaderRoute: typeof AppEstadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppEstadosRoute: typeof AppEstadosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFornecimentosRoute: typeof AppFornecimentosRoute
  AppMarcasRoute: typeof AppMarcasRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppProcessosRoute: typeof AppProcessosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppEstadosRoute: AppEstadosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFornecimentosRoute: AppFornecimentosRoute,
  AppMarcasRoute: AppMarcasRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppProcessosRoute: AppProcessosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
